-- Adminer 4.7.2 MySQL dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `recipeList`;
CREATE TABLE `recipeList` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `title` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `ingredients` varchar(8000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `directions` varchar(8000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `dishPicture` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `recipeList_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `recipeUser` (`userid`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `recipeList` (`id`, `user_id`, `title`, `date`, `ingredients`, `directions`, `dishPicture`) VALUES
(2,	2,	'Home Made Chili',	'2020-12-09 15:58:33',	'1 tablespoon olive oil\r\n1 medium yellow onion -diced\r\n1 pound 90% lean ground beef\r\n2 1/2 tablespoons chili powder\r\n2 tablespoons ground cumin\r\n2 tablespoons granulated sugar\r\n2 tablespoons tomato paste\r\n1 tablespoon garlic powder\r\n1 1/2 teaspoons salt\r\n1/2 teaspoon ground black pepper\r\n1/4 teaspoon ground cayenne pepper* -optional\r\n1 1/2 cups beef broth\r\n1 (15 oz.) can petite diced tomatoes\r\n1 (16 oz.) can red kidney beans, drained and rinsed\r\n1 (8 oz.) can tomato sauce',	'1.) Add the olive oil to a large soup pot and place it over medium-high heat for two minutes. Add the onion. Cook for 5 minutes, stirring occasionally.\r\n\r\n2.) Add the ground beef to the pot. Break it apart with a wooden spoon. Cook for 6-7 minutes, until the beef is browned, stirring occasionally.\r\n\r\n3.) Add the chili powder, cumin, sugar, tomato paste, garlic powder, salt, pepper, and optional cayenne. Stir until well combined.\r\n\r\n4.) Add the broth, diced tomatoes (with their juice), drained beans, and tomato sauce. Stir well.\r\n\r\n5.) Bring the liquid to a low boil. Then, reduce the heat (low to medium-low) to gently simmer the chili, uncovered, for 20-25 minutes, stirring occasionally.\r\n\r\n6.) Remove the pot from the heat. Let the chili rest for 5-10 minutes before serving.',	'beef-chili-with-beans-8354b3.jpg'),
(3,	2,	'Banana Bread',	'2020-12-09 16:05:13',	'2 cups (250g) all-purpose flour (spoon & leveled)\r\n1 teaspoon baking soda\r\n1/4 teaspoon salt\r\n1/2 teaspoon ground cinnamon\r\n1/2 cup (1 stick or 115g) unsalted butter, softened to room temperature\r\n3/4 cup (150g) packed light or dark brown sugar\r\n2 large eggs, at room temperature\r\n1/3 cup (80g) plain yogurt or sour cream (I use Greek yogurt)\r\n2 cups mashed bananas (about 4 large ripe bananas)\r\n1 teaspoon pure vanilla extract\r\noptional: 3/4 cup (100g) chopped pecans or walnuts',	'1.) Adjust the oven rack to the lower third position and preheat the oven to 350°F (177°C).\r\n\r\n2.)Grease a 9×5-inch loaf pan or coat with nonstick spray. Set aside.\r\n\r\n3.) Whisk the flour, baking soda, salt, and cinnamon together in a large bowl.\r\n\r\n4.)Using a handheld or stand mixer fitted with a paddle or whisk attachment, beat the butter and brown sugar together on high speed until smooth and creamy, about 2 minutes. On medium speed, add the eggs one at a time, beating well after each addition. Beat in the yogurt, mashed bananas, and vanilla extract on medium speed until combined. \r\n\r\n5.)With the mixer running on low speed, slowly beat the dry ingredients into the wet ingredients until no flour pockets remain. Do not overmix. Fold in the nuts, if using.\r\n\r\n6.) Spoon the batter into the prepared baking pan and bake for 60-65 minutes. Loosely cover the bread with aluminum foil after 30 minutes to help prevent the top and sides from getting too brown. A toothpick inserted in the center of the loaf will come out clean when the bread is done. Remove from the oven and allow the bread to cool completely in the pan set on a wire rack.\r\n\r\n7.) Cover and store banana bread at room temperature for 2 days or in the refrigerator for up to 1 week. Banana bread tastes best on day 2 after the flavors have settled together. See post above for freezing instructions.',	'BananBread.jpg'),
(4,	3,	'Family Lasagna',	'2020-12-09 16:09:42',	'1 Tablespoon olive oil\r\n1 small onion diced\r\n1 pound ground beef\r\n1 pound Italian sausage\r\n1 28 Ounce can crushed tomatoes\r\n2 6.5 ounce can tomato sauce\r\n1 6 ounce can tomato paste\r\n2 Tablespoons Italian Seasoning\r\n1/4 cup sugar\r\nsalt and pepper to taste\r\n1 tablespoon fresh basil chopped\r\n12 lasagna noodles\r\n16 ounce ricotta cheese\r\n\r\n1/2 cup parmesan finely grated\r\n1 egg\r\n2 cups mozzarella cheese shredded',	'1.) In a large skillet over medium high heat add the olive oil and onion. Sauté until tender and add the ground beef and sausage. Cook and crumble until brown and cooked throughout. Add crushed tomatoes, tomato sauce, tomato paste, Italian seasoning, sugar, and basil. Let simmer on low heat.\r\n\r\n2.) In a large pot, bring the water to a boil. Add the lasagna noodles and cook for 8-10 minutes. Drain and rinse in cold water.\r\n\r\n3.) In medium sized bowl add the ricotta cheese, parmesan, and egg. Mix until incorporated.\r\nPreheat oven to 375 degrees and spray a 9x13 inch pan with non stick spray and set aside.\r\n\r\n4.) To make the lasagna start by spreading 1 cup of the meat sauce on the bottom. Arrange the noodles in a single layer over the meat sauce. Spread 1/2 cup of the ricotta cheese, on top of the noodles followed by shredded mozzarella cheese. Repeat the layers and top with cheese.\r\n\r\n5.) Cover with aluminum foil and bake for 20 minutes. Remove the foil and bake and additional 20-25 minutes or until it is heated throughout and cheese is bubbly. Let it cool for 10 minutes before serving.',	'Lasagna.jpg'),
(5,	3,	'Ginger Bread Cookies',	'2020-12-09 16:12:27',	'10 Tablespoons (2/3 cup; 145g) unsalted butter, softened to room temperature\r\n3/4 cup (150g) packed light or dark brown sugar\r\n2/3 cup (200g) unsulphured molasses\r\n1 large egg, at room temperature\r\n1 teaspoon pure vanilla extract\r\n3 and 1/2 cups (437g) all-purpose flour (spoon & leveled)\r\n1 teaspoon baking soda\r\n1/2 teaspoon salt\r\n1 Tablespoon ground ginger (yes, 1 full Tablespoon!)\r\n1 Tablespoon ground cinnamon\r\n1/2 teaspoon ground allspice\r\n1/2 teaspoon ground cloves',	'1.) In a large bowl using a hand-held mixer or stand mixer fitted with a paddle attachment, beat the butter for 1 minute on medium speed until completely smooth and creamy. Add the brown sugar and molasses and beat on medium high speed until combined and creamy-looking. Scrape down the sides and bottom of the bowl as needed. Next, beat in egg and vanilla on high speed for 2 full minutes. Scrape down the sides and bottom of the bowl as needed. The butter may separate; that’s ok.\r\n\r\n2.) In a separate bowl, whisk the flour, baking soda, salt, ginger, cinnamon, allspice, and cloves together until combined. On low speed, slowly mix into the wet ingredients until combined. The cookie dough will be quite thick and slightly sticky. Divide dough in half and place each onto a large piece of plastic wrap. Wrap each up tightly and pat down to create a disc shape. Please see photo and description above in my post. Chill discs for at least 3 hours and up to 3 days. Chilling is mandatory for this cookie dough. I always chill mine overnight.\r\n\r\n3.) Preheat oven to 350°F (177°C). Line 2-3 large baking sheets with parchment paper or silicone baking mats. (Always recommended for cookies.) Set aside.\r\n\r\n4.) Remove 1 disc of chilled cookie dough from the refrigerator. Generously flour a work surface, as well as your hands and the rolling pin. Don’t be afraid to continually flour the work surface as needed- this dough can be sticky. Roll out disc until 1/4-inch thick. Cut into shapes. Place shapes 1 inch apart on prepared baking sheets. Re-roll dough scraps until all the dough is shaped. Repeat with remaining disc of dough.\r\n\r\n5.) Bake cookies for about 9-10 minutes. If your cookie cutters are smaller than 4 inches, bake for about 8 minutes. If your cookie cutters are larger than 4 inches, bake for about 11 minutes. My oven has hot spots and yours may too- so be sure to rotate the pan once during bake time.\r\n\r\n6.) Allow cookies to cool for 5 minutes on the cookie sheet. Transfer to cooling rack to cool completely. Once completely cool, decorate as desired.\r\n\r\nCookies stay fresh covered at room temperature for up to 1 week.',	'gingerbreadcookie.jpg'),
(6,	3,	'Parmesan Chicken',	'2020-12-09 16:16:02',	'For The Chicken:\r\n2 large eggs\r\n1 tablespoon minced garlic\r\n2 tablespoons fresh chopped parsley\r\nSalt and pepper to season\r\n3 large chicken breasts halved horizontally to make 6 fillets\r\n1 cup Panko breadcrumbs\r\n1/2 cup breadcrumbs (Italian or golden)\r\n1/2 cup fresh grated parmesan cheese\r\n1 teaspoon garlic or onion powder\r\n1/2 cup olive oil for frying\r\nFor The Sauce:\r\n1 tablespoon olive oil\r\n1 large onion chopped\r\n2 teaspoons minced garlic\r\n14 ounces (400 g) tomato puree (Passata)\r\nSalt and pepper to taste\r\n1 teaspoon dried Italian herbs\r\n1 teaspoon sugar (optional)\r\nFor The Topping:\r\n8 ounces (250 g) mozzarella cheese sliced or shredded\r\n1/3 cup fresh shredded parmesan cheese\r\n2 tablespoons fresh chopped basil or parsley',	'For The Chicken:\r\n1.) Preheat oven 430°F | 220°C. Lightly grease an oven tray (or baking dish) with non stick cooking oil spray; set aside.\r\n\r\n2.) Whisk together eggs, garlic, parsley, salt and pepper in a shallow dish. Add chicken into the egg, rotating to evenly coat each fillet in the mixture. Cover with plastic wrap and allow to marinate for at least 15 minutes (or overnight night if time allows for a deeper flavour).\r\n\r\n3.) When chicken is ready for cooking, mix bread crumbs, Parmesan cheese and garlic powder together in a separate shallow bowl. Dip chicken into the breadcrumb mixture to evenly coat.\r\n\r\n4.) Heat oil in a large skillet over medium-high heat until hot and shimmering. Fry chicken until golden and crispy, (about 4-5 minutes each side).\r\n\r\n5.) Place chicken on prepared baking tray / dish and top each breast with about 1/3 cup of sauce (sauce recipe below). Top each chicken breast with 2-3 slices of mozzarella cheese and about 2 tablespoons parmesan cheese. Sprinkle with basil or parsley. \r\n\r\n6.) Bake for 15-20 minutes, or until cheese is bubbling and melted, and the chicken is completely cooked through.\r\n\r\nFor The Sauce:\r\n1.) Heat oil in a medium-sized pot. Fry onion until transparent (about 3 minutes), then add the garlic until fragrant (about 30 seconds).\r\n\r\n2.) Add the tomato puree, salt and pepper to taste, Italian herbs and sugar (If using). Cover with lid to simmer for about 8 minutes, or until sauce has thickened slightly. Taste test and adjust salt and pepper, if needed.',	'parmchicken.jpg'),
(7,	2,	'Chicken Alfredo',	'2020-12-09 16:19:50',	'Kosher salt and freshly ground black pepper\r\n\r\n12 ounces fettuccine\r\n\r\nOlive oil, for tossing\r\n\r\n12 ounces boneless, skinless chicken breast (about 2) \r\n\r\n1 stick (8 tablespoons) unsalted butter\r\n\r\n2 cups heavy cream\r\n\r\n2 pinches freshly grated nutmeg\r\n\r\n1 1/2 cups freshly grated Parmigiano-Reggiano \r\n',	'1.) Bring a large pot of water to a boil, and salt generously. Add the pasta and cook according to package directions until al dente (tender but still slightly firm). Drain and toss with a splash of oil.\r\n\r\n2.) Meanwhile, slice the chicken into 1/4-inch-thick strips, and lay them on a plate or a sheet of waxed paper. Season with salt and pepper.\r\n\r\n3.) Heat a large skillet over medium heat. Add 2 tablespoons of the butter. When the butter melts, raise the heat to medium-high and add the chicken in 1 layer. Cook, without moving the pieces, until the underside has browned, 1 to 2 minutes. Flip the pieces, and cook until browned and cooked through, 2 to 3 minutes more. Transfer the chicken to a medium bowl.\r\n\r\n4.) Reduce the heat to medium. Add the remaining 6 tablespoons butter. Scrape the bottom of the skillet with a wooden spoon to release any browned bits. When the butter has mostly melted, whisk in the cream and nutmeg and bring to a simmer, then cook for 2 minutes. Lower the heat to keep the sauce just warm.\r\n\r\n5.) Whisk the Parmigiano-Reggiano into the sauce. Add the chicken and cooked pasta and toss well. Season with salt and pepper. Serve hot in heated bowls.',	'chickenalfredo.jpg'),
(8,	4,	'Baked Salmon',	'2020-12-09 16:31:18',	'2 pound side of salmon boneless (skin on or off, depending upon your preference), wild caught if possible\r\n5 sprigs fresh rosemary or fresh herbs of your choice; do not use dried herbs\r\n2 small lemons divided, plus extra for serving as desired\r\n2 tablespoons extra virgin olive oil\r\n1 teaspoon kosher salt\r\n1/4 teaspoon ground black pepper\r\n4 cloves garlic peeled and roughly chopped\r\nAdditional chopped fresh herbs such as basil, thyme, parsley, dill, or green onion (optional)',	'1.) Remove the salmon from the refrigerator and let stand at room temperature for 10 minutes while you prepare the other ingredients. Heat oven to 375 degrees F. Line a large baking dish or rimmed baking sheet with a large piece of aluminum foil.\r\n\r\n2.) Lightly coat the foil with baking spay, then arrange 2 sprigs of the rosemary down the middle. Cut one of the lemons into thin slices and arrange half the slices down the middle with the rosemary. Place the salmon on top.\r\n\r\n3.) Drizzle the salmon with the olive oil and sprinkle with the salt and pepper. Rub to coat, then scatter the garlic cloves over the top. Lay the remaining rosemary and lemon slices on top of the salmon. Juice the second lemon, then pour the juice over the top.\r\n\r\n4.) Bake the salmon for 15-20 minutes, until the salmon is almost completely cooked through at the thickest part. The cooking time will vary based on the thickness of your salmon. If your side is thinner (around 1-inch thick) check several minutes early to ensure your salmon does not overcook. If your piece is very thick (1 1/2 inches or more), it may need longer.\r\n\r\n5.) Remove the salmon from the oven and carefully open the foil so that the top of the fish is completely uncovered (be careful of hot steam). Change the oven setting to broil, then return the fish to the oven and broil for 3 minutes, until the top of the salmon and the garlic are slightly golden and the fish is cooked through. \r\n\r\nNOTES: Watch the salmon closely as it broils to make sure it doesn’t overcook and the garlic does not burn. Remove the salmon from the oven. If it still appears a bit underdone, you can wrap the foil back over the top and let it rest for a few minutes. Do not let it sit too long—salmon can progress from \"not done\" to \"over done\" very quickly. ',	'bakedsalmoninfoil.jpg'),
(9,	4,	'Garlic Butter Tilapia',	'2020-12-09 16:33:43',	'Tilapia Fillets: This recipe uses four medium-sized fillets.\r\nSalt and Pepper\r\nDried Thyme, Dried Oregano, and Ground Paprika: Use regular paprika, not hot or smoked paprika.\r\nButter: You’ll need 4 tablespoons, melted.\r\nFresh Garlic: Mince the garlic or put it through a garlic press.\r\nFresh Lemon Juice and Lemon Zest: You’ll need two tablespoons of juice and ¼ teaspoon of zest.\r\nLemon Slices, Red Pepper Flakes, and Chopped Parsley: For garnish.',	'1.) Prepare the Tilapia Fillets. Season tilapia with salt, pepper, paprika, thyme, and oregano; arrange fish in a 9×13 baking dish. \r\n\r\n2.) In a mixing bowl, whisk together melted butter, garlic, lemon juice, and lemon zest; pour over tilapia.\r\n\r\n3.) Bake the Fillets. Bake tilapia for 10 to 12 minutes, or until fish flakes and is fork-tender.\r\n\r\n4.) Serve! Garnish with pepper flakes, parsley, and lemon slices and enjoy!',	'tilapia.jpg'),
(10,	4,	'Goulash',	'2020-12-09 16:37:43',	'1 tbsp olive oil\r\n1 cup onion, diced\r\n1 green bell pepper, diced\r\n2 lbs. ground beef, lean\r\n3 tsp garlic, minced\r\n2 15 oz cans tomato sauce\r\n2 15 oz cans petite diced tomatoes\r\n3 cups beef broth\r\n3 tbsp Worcestershire Sauce\r\n2 tsp seasoned salt\r\n2 tbsp Italian Seasoning\r\n3 bay leaves\r\n2 cups macaroni noodles, uncooked\r\n1 cup cheddar cheese, shredded',	'1.) Add olive oil to large pot over medium-high heat. Add in the onion, bell pepper and ground beef then cook until beef is no longer pink.\r\n\r\n2.) Drain any excess fat and return pot to stove top. Add in garlic and stir until fragrant (about 30 seconds).\r\n\r\n3.) Pour in the tomato sauce, diced tomatoes, beef broth, Worcestershire sauce, seasoned salt, Italian seasoning, bay leaves and dried macaroni noodles. Stir and bring mixture to a boil. \r\n\r\n4.) Reduce heat to a light boil and stir occasionally until the pasta is tender, about 20 minutes.\r\n\r\n5.) Remove the bay leaves and stir in the cheddar cheese just before serving. Enjoy!',	'goulash.jpeg'),
(11,	4,	'Chocolate Cake',	'2020-12-09 16:39:35',	'2 cups all-purpose flour\r\n2 cups sugar\r\n3/4 cup unsweetened cocoa powder\r\n2 teaspoons baking powder\r\n1 1/2 teaspoons baking soda\r\n1 teaspoon salt\r\n1 teaspoon espresso powder homemade or store-bought\r\n1 cup milk buttermilk, almond, or coconut milk\r\n1/2 cup vegetable oil canola oil, or melted coconut oil\r\n2 large eggs\r\n2 teaspoons vanilla extract\r\n1 cup boiling water\r\nChocolate Buttercream Frosting Recipe',	'1.) Preheat oven to 350º F. Prepare two 9-inch cake pans by spraying with baking spray or buttering and lightly flouring.\r\n\r\nFor the chocolate cake:\r\n2.) Add flour, sugar, cocoa, baking powder, baking soda, salt and espresso powder to a large bowl or the bowl of a stand mixer. Whisk through to combine or, using your paddle attachment, stir through flour mixture until combined well.\r\n\r\n3.) Add milk, vegetable oil, eggs, and vanilla to flour mixture and mix together on medium speed until well combined. \r\n\r\n4.) Reduce speed and carefully add boiling water to the cake batter until well combined.\r\n\r\n5.) Distribute cake batter evenly between the two prepared cake pans. Bake for 30-35 minutes, until a toothpick or cake tester inserted in the center of the chocolate cake comes out clean.\r\n\r\n6.) Remove from the oven and allow to cool for about 10 minutes, remove from the pan and cool completely.\r\n\r\n7.) Frost cake with Chocolate Buttercream Frosting.',	'chocolatecake.jpg');

DROP TABLE IF EXISTS `recipeUser`;
CREATE TABLE `recipeUser` (
  `userid` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `password` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `recipeUser` (`userid`, `username`, `password`) VALUES
(2,	'fraisbeck',	'a6b8b600c27ce95ddcf867cfc503564c89fe816a'),
(3,	'Steph',	'6c3910c829ca7a8cb43267e85faf60e01708b0cd'),
(4,	'Luna',	'baaf10f1b4838977a6163141ffd45a629ee11514');

-- 2020-12-11 23:58:47
